name: Check Google Sheet for Positive Balance

on:
  schedule:
    - cron: '0 6-21 * * *' # Jede Stunde von 6 bis 22 Uhr MEZ

jobs:
  check-sheet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Python Script
      run: python check_sheet.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add output.json
        git commit -m "Update output.json with latest positive balance month" || echo "No changes to commit"
        git push
